std = "roblox+testez"

[rules]
almost_swapped = "deny"
divide_by_zero = "deny"
duplicate_keys = "deny"
empty_if = "warn"
global_usage = "deny"
if_same_then_else = "warn"
ifs_same_cond = "warn"
one_line_if = "allow"
mismatched_arg_count = "warn"
parenthese_condition = "allow"
roblox_incorrect_color3_new_bounds = "deny"
roblox_incorrect_roact_usage = "deny"
shadowing = "warn"
incorrect_standard_library_use = "deny"
suspicious_reverse_loop = "deny"
type_check_inside_call = "deny"
unbalanced_assignments = "deny"
undefined_variable = "deny"
unscoped_variables = "deny"
unused_variable = "warn"
